# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
